# Paramètres globaux
#persistence true
#persistence_location /var/lib/mosquitto/
#log_dest file /var/log/mosquitto.log

# Auditeurs
listener 1883
listener 8883
protocol websockets # Activer WebSockets pour un auditeur

# Authentification
allow_anonymous false
password_file /mosquitto/config/passwords.txt

#persistance
#persistence true # Activer la persistance des messages et des abonnements
#persistence_file mosquitto.db # Nom du fichier de persistance
#persistence_location /mosquitto/data/ # Emplacement du fichier de persistance
#autosave_interval 1800 # Sauvegarde automatique toutes les 30 minutes

#log
#log_dest file /mosquitto/log/mosquitto.log # Destination des journaux
