services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
  hems:
    build: ./HEMS
    container_name: hems
    ports:
      - "5000:5000"
    environment:
      - MQTT_USER=your_user
      - MQTT_PASSWORD=your_password
    depends_on:
      - mqtt
    restart: unless-stopped